### PR TITLE
mu4e: Allow "washing" of URLs in message view

### PR DESCRIPTION
**Pull request by rotty**
See the commit message for details; this PR does not yet include
documentation changes, as I first want to check whether this is (in
principle) considered a reasonable addition to mu4e.

### CODE REVIEW

**Comment by Chris00** [comment]
I glanced over your code but it does not seem to also target the Gnus-based viewer (which *may* become the default in some time...).

**Comment by rotty** [comment]
Yeah, I've realized that after coding the patch, and was not motivated enough to address the Gnus view, since I had a solution that addressed my immediate issue; I'll take a look at what implementing this based on the Gnus article view would entail.

**Comment by djcb** [comment]
Effort certainly appreciated, but yeah, we're trying to avoid any updates to the "old" mu4e-view.

Could this be used with the gnus-view? Or perhaps there's something like that there already?
There's https://www.gnu.org/software/emacs/manual/html_node/gnus/Article-Washing.html at least.

**Comment by Chris00** [comment]
On 27 February 2020 at 00:23 CET, Dirk-Jan C. Binnema <notifications@github.com> wrote:
>
> Effort certainly appreciated, but yeah, we're trying to avoid any updates to the "old" mu4e-view.
>
> Could this be used with the gnus-view? Or perhaps there's something like that there already?  There's https://www.gnu.org/software/emacs/manual/html_node/gnus/Article-Washing.html at least.

At least we wan try to piggyback on that — at the moment, these commands return `gnus-summary-select-article: This is a pseudo-article`.

**Comment by djcb** [comment]
Yeah, all those commands expect the "Summary buffer" (similar to our headers-view) to do something. Not sure if the gnus people would be interested in changing that, and/or how far we could get with e.g. advising functions. I'd like to avoid including modified versions as part of mu4e.

**Comment by Chris00** [comment]
On 27 February 2020 at 08:45 CET, Dirk-Jan C. Binnema <notifications@github.com> wrote:
>
> Yeah, all those commands expect the "Summary buffer" (similar to our headers-view) to do something. Not sure if the gnus people would be interested in changing that, and/or how far we could get with e.g. advising functions. I'd like to avoid including modified versions as part of mu4e.

Advising it would likely do the trick — that was the point of introducing the local variable `mu4e~view-rendering`.

**Comment by djcb** [comment]
Okay, guess this is obsolete then.

**Pull request closed without merging**
