### PR TITLE
mu4e-mark: Allow executing marks without passing a prefix argument

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by djcb** [comment]
Hmm, calling this without a prefix argument works just fine... did you you mean calling it non-interactively?

**Comment by Chris00** [comment]
Sometimes the following is triggered (with debugger on);
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  mu4e-mark-execute-all()
  mu4e-view-marked-execute()
  funcall-interactively(mu4e-view-marked-execute)
  call-interactively(mu4e-view-marked-execute nil nil)
  command-execute(mu4e-view-marked-execute)
```
Sometimes it works...  A bit puzzled.

**Comment by Chris00** [comment]
I recompiled it and now I only have the error...

**Comment by djcb** [comment]
Guess the "interactiveness" doesn't propagate.. anyway, the optional should fix that, thanks!

**Pull request merged**
