### PR TITLE
Mu4e: Added missing menu items.

### PR DESCRIPTION
**Pull request by tmalsburg**
Menu items for threading and include-related in header view.

### CODE REVIEW

**Comment by djcb** [comment]
Oh, what would be even nicer to have the items shown as toggles - ie., like some of the items in the emacs "Options" menu. Can you do that?

**Comment by tmalsburg** [comment]
I'll find out how to do it.  But I won't be able to work on it until the end of next week.

**Comment by tmalsburg** [comment]
Wait, this is easy.  I'll amend the PR.

**Comment by tmalsburg** [comment]
Ok, I updated the PR.

**Comment by djcb** [comment]
Finally merged this -- sorry for the delay. Thanks!

**Comment by tmalsburg** [comment]
No problem, thanks.

**Pull request merged**
