### PR TITLE
Add reply-to argument to mu4e-compose-reply

### PR DESCRIPTION
**Pull request by zakkak**
Make mu4e-compose-reply take an optional argument that shows whether
the reply should be to all recipients or only to the sender.
#373 and #542 related

### CODE REVIEW

**Comment by adam353** [comment]
This functionality would be incredibly useful to those of us who greatly desire separate single-key bindings for "reply" and "reply all" from *mu4e-view* (as mutt does).  Please consider merging this request.

**Comment by zakkak** [comment]
@djcb Any comments on this?

**Comment by Ambrevar** [comment]
Any update?

**Comment by djcb** [comment]
Don't really want to change so much code to save one keystroke... so am going to close this old PR.

**Pull request closed without merging**
