### PR TITLE
Fix mu4e-view-mode-hook not called on unread messages

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
Fix #1265 and #1267.

Here's the problem:

When `mu4e~view-internal` is called it makes a call to
`mu4e~view-mark-as-read-maybe`.
When the message is unread `mu4e~view-mark-as-read-maybe` calls
`mu4e~proc-move` which flag the message as read and calls again
`mu4e~view-internal` which in turn calls again
`mu4e~view-mark-as-read-maybe` which this time returns nil and
`mu4e~view-internal` continues printing the view buffer and running
hooks.
Then `mu4e~view-mark-as-read-maybe` first call continue to run and
calls now `mu4e~proc-view` which as `mu4e~proc-move` calls again
`mu4e~view-internal` and prints a second time the buffer and run a
second time the hooks.

The first thing this patch does is always running hooks after printing
message, then to avoid doing this again it advice temporarily
`mu4e-view-func` aka `mu4e~view-internal` to prevent printing and
running hooks again.
Finally this advice function remove itself the advice to allow
printing the next message.

* mu4e/mu4e-view.el (mu4e~view-internal): Remove mode-enabled checking
which is useless.
(mu4e~view-advice-view-func): Advice mu4e-view-func to ensure it
doesn't run a second time.
(mu4e~view-mark-as-read-maybe): Use it.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
This PR fix as well #1192 and possibly #1217

**Comment by thierryvolpiatto** [comment]
@djcb ping

**Comment by djcb** [comment]
Hmmm, using `advise` here seems a bit unnecessary since we control the code ourselves, or?

 I'd prefer a solution where  `mu4e~view-mark-as-read-maybe` returns `t` if actually marks the message, and we can do something like: 
```
(unless (mu4e~view-mark-as-read-maybe) 
       ... view the message, run hooks etc.)
```
then, we also run the hooks on the message the user actually sees (rather than still-unread one)

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Hmmm, using advise here seems a bit unnecessary since we control the
> code ourselves, or?

Did you read the commit message and comments?

      ;; When MSG is unread, mu4e~view-mark-as-read-maybe will trigger
      ;; 2 other calls to mu4e~view-internal when running
      ;; mu4e~proc-move and mu4e~proc-view. To avoid printing and
      ;; running hooks a second time we advice mu4e-view-func aka
      ;; mu4e~headers-view-handler aka mu4e-view aka
      ;; mu4e~view-internal so that it does nothing. See
      ;; mu4e~view-mark-as-read-maybe and mu4e~view-advice-view-func.

So if you don't advise `mu4e-view-func`, `mu4e~proc-view` will print a
second time the buffer and also run hook a second time.

> I'd prefer a solution where mu4e~view-mark-as-read-maybe returns t if
> actually marks the message, and we can do something like:

Of course it would be better but it is not possible unless you change
the signature of some functions to accept an extra optional arg that say
"buffer is printed and hook already ran so do nothing now".

In this patch we are using `add-function` which is exactly the tool
needed for such cases, it affects nothing else as the advice function
remove itself when it run and finally avoid doing complex changes in
sensible function that may break something else.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
```
mu4e~view-internal
    => mu4e~view-mark-as-read-maybe
       => mu4e~proc-move
          => mu4e~view-internal
             => mu4e~view-mark-as-read-maybe -> nil (print buffer and run hooks)
                => mu4e~proc-view
                   => mu4e~view-internal
                      => mu4e~view-mark-as-read-maybe -> nil (print buffer and run hooks)[2th]
       => t
```

**Comment by seanfarley** [comment]
Gentle ping

**Comment by djcb** [comment]
When setting `mu4e-view-mode-hook` to something like
```
(add-hook 'mu4e-view-mode-hook
  (lambda()
    (message "running mu4e-view-mode-hook")))
```
I see that message only exactly once for either read or unread messages.. so under what circumstances does this fail?

And indeed, I would prefer changing functions to do the right things, I'd consider advice only for code one cannot otherwise change.

**Comment by seanfarley** [comment]
I don't see how that's possible and even tested it just now. For me, your hook doesn't run on unread messages.

I am deterred from helping out any more since you seem so flippant in your response. There is much discussion in your own project on this behavior that happened *two months ago*:

* https://github.com/djcb/mu/pull/1265
* https://github.com/djcb/mu/pull/1267

I'll continue to monkey patch and fix this myself since you don't seem to have the time.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> When setting mu4e-view-mode-hook to something like
>
> (add-hook 'mu4e-view-mode-hook
>   (lambda()
>     (message "running mu4e-view-mode-hook")))
>
> I see that message only exactly once for either read or unread
> messages..

Hmm...

> so under what circumstances does this fail?

Unread messages, read the commit message of my patch, it is all explained.

> And indeed, I would prefer changing functions to do the right things,

If you want to do this, consider rewriting a bunch of things in
mu4e-proc...

> I'd consider advice only for code one cannot otherwise change.

This is not advice, well not really, it is `add-function` which have
been conceived to interact from inside source code, in contrast with
`advice-add` which is to interact with source code from outside
i.e. user side.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Sean Farley <notifications@github.com> writes:

> I don't see how that's possible and even tested it just now. For me,
> your hook doesn't run on unread messages.

Agree.

> I'll continue to monkey patch and fix this myself since you don't seem to have the time.

Same here.

-- 
Thierry

**Comment by djcb** [comment]
"flippant"? Let's assume good faith, shall we?

**Comment by djcb** [comment]
So, I think this should be fixed now (even if in a slightly different way). Thanks for taking the time.

**Comment by thierryvolpiatto** [comment]
I have updated mu and @djcb FYI your fix is still not working.
Only https://github.com/thierryvolpiatto/mu/tree/mu4e-view-mode-hook_fix is working for me for now.
IIRC What you did was good but insufficient, you need to merge your changes with my branch (fully not tested).

**Comment by djcb** [comment]
Hmmm... it works for me. Ie.,
```
(setq mu4e-view-use-gnus nil)
(add-hook 'mu4e-view-mode-hook
  (lambda() (message "running mu4e-view-mode-hook")))
```

And I can see the `message` for each message I open (unread or not). Do you see something else?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Hmmm... it works for me. Ie.,
>
> (setq mu4e-view-use-gnus nil)
> (add-hook 'mu4e-view-mode-hook
>   (lambda() (message "running mu4e-view-mode-hook")))
>
> And I can see the message for each message I open (unread or not). Do you see something else?

Yes smileys are not activated with read or unread messages.
(add-hook 'mu4e-view-mode-hook 'smiley-buffer)

-- 
Thierry

**Comment by djcb** [comment]
So, the hook does run, but it runs a bit too early for smiley-mode to anything useful. I've pushed a change so the hooks run later, and that seems to work. For you as well, @thierryvolpiatto ?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> So, the hook does run, but it runs a bit too early for smiley-mode to
> anything useful. I've pushed a change so the hooks run later, and that
> seems to work.  For you as well, @thierryvolpiatto ?

Seems to work fine now, thanks ;-).

--
Thierry

**Comment by tasmo** [comment]
> Hmmm... it works for me. Ie.,
> 
> ```
> (setq mu4e-view-use-gnus nil)
> (add-hook 'mu4e-view-mode-hook
>   (lambda() (message "running mu4e-view-mode-hook")))
> ```
> 
> And I can see the `message` for each message I open (unread or not). Do you see something else?

Unfortunately it does not work here. The message appears in read emails but not when I open unread.

**Pull request closed without merging**
