### PR TITLE
mu4e/ical: Compose the response attaching the calendar

### PR DESCRIPTION
**Pull request by Chris00**
This composes the response before any hook is run which is important so that, if those hooks modify the message, they are aware that some MML is present.  In particular, this is needed to have the compatibility with the org-msg package; see https://github.com/djcb/mu/issues/1956

### CODE REVIEW

**Comment by Chris00** [comment]
@baracunatana @hughwilliams94 This is a slightly different take on the composition of iCal replies.  May you help me to test it by making sure it works in your environments — it does in mine.

This is the *mu4e* part in order to [org-msg](https://github.com/jeremy-compostella/org-msg) not to activate for [ical replies](https://github.com/djcb/mu/issues/1956).  (There will be a part for org-msg as well — which will also fix the [problem with Forward](https://github.com/jeremy-compostella/org-msg/issues/92) — but I'd like first to have [other](https://github.com/jeremy-compostella/org-msg/pull/91) [PR](https://github.com/jeremy-compostella/org-msg/pull/93) merged.)

**Comment by Chris00** [comment]
The [org-msg patch](https://github.com/jeremy-compostella/org-msg/pull/95).

**Comment by Chris00** [comment]
@baracunatana @hughwilliams94 If you wish, you can send me an invite (email in my profile) and I'll *accept* it.

**Comment by hughwilliams94** [comment]
I'm a little swamped by work currently so can't test on my setup right now. I've sent a test invite to you at your profile email.

**Comment by Chris00** [comment]
Thanks.  Just accepted it.

**Comment by Chris00** [comment]
@hughwilliams94 When you have time, please let us know whether you see your iCal invitation as accepted.

**Comment by Chris00** [comment]
@hughwilliams94 I saw that you cancelled the meeting but it is not clear to me whether my *accepted* answer worked.

**Comment by hughwilliams94** [comment]
Sorry the accept did come through fine thanks!

**Comment by Chris00** [comment]
@hughwilliams94 Thanks for your help!

**Comment by Chris00** [comment]
@djcb I think this is ready to be considered for merge.

**Comment by djcb** [comment]
Ok, let's merge this then. Thanks!

**Comment by baracunatana** [comment]
Can confirm that it now works as intended one you apply the MML patch to [org-msg](https://github.com/djcb/mu/pull/1967#issuecomment-814055914)

**Pull request merged**
