### PR TITLE
Perl interface

### PR DESCRIPTION
**Pull request by StAlphonsos**
This was originally https://github.com/StAlphonsos/mup

I've tried to hew to your style in the autotools stuff; I've used
autoconf extensively but never automake so please forgive any
egregious mistakes.

### CODE REVIEW

**Comment by StAlphonsos** [comment]
Ping?

**Comment by djcb** [comment]
Oh, only saw this now, sorry for the delay Interesting stuff! We'll do a new release in the next days or so, let's see if we can integrate it afterwards.

**Comment by djcb** [comment]
So, I'm ready to merge this, do you have any changes still?

**Comment by StAlphonsos** [comment]
No, I haven't had to modify it since the pull request.
Thanks!

**Comment by djcb** [comment]
The change breaks `make check' (the unit tests). Can you fix that?

**Comment by StAlphonsos** [comment]
Taking a look...

**Comment by StAlphonsos** [comment]
Okay, I'm a bit confused.  I just pulled master from your repo, branched off of it and merged my Perl interface branch onto it.  No problem.  I then autoreconf'ed and used the following invocation:
```
$ configure --enable-perl --disable-gtk --disable-webkit --disable-guile`
```
The results of `gmake test` are not constant.  The first time I did it
it resulted in this error:
```
  ...
  /mu-maildir/mu-maildir-walk-with-noupdate:                           mkdir: /tmp/mu-test-1000/test-bc5f7a9c: File exists OK
  /mu-maildir/mu-maildir-get-new-path-new:                             **
ERROR:test-mu-maildir.c:440:assert_matches_regexp: assertion failed: (0)
FAIL
GTester: last random seed: R02Sa11ce2f33319559ceb6910e20b622129
Terminated 
Makefile:836: recipe for target 'test' failed
```

I got this error twice times in the course of typing `gmake test` ten times or so.  The other times I've run `gmake test` it wins all the way through, including the new Perl tests.  In fact the Perl tests have not failed for me yet.

It might be something in my environment I'm not thinking of.  I'm not sure.  Could you give me more details on how `gmake test` is breaking for you?

**Comment by StAlphonsos** [comment]
Argh! You said "make check" not "make test". Re-examining my world now...

**Comment by StAlphonsos** [comment]
Argh! You said "make check" not "make test". I have a fix. Sorry. Didn't notice the "check" target.

**Comment by StAlphonsos** [comment]
Okay, latest commit to this branch should fix the problem.

**Comment by djcb** [comment]
Okay, now it passes all tests -- great. So, final step: can you rebase against master and squash your patches into 1, and prefix the commit summary with "perl:"? Then I'll merge it -- Thanks!

Ohw, and perhaps (after I've added it), you can write a message to the mailing list announcing this? It's a nice feature!

**Comment by djcb** [comment]
Any update on this?

**Comment by djcb** [comment]
ping?

**Comment by djcb** [comment]
This seems to have staled... closing this for now.

**Pull request closed without merging**
