### PR TITLE
perl: Integrate the mup interface from https://github.com/StAlphonsos/mup

### PR DESCRIPTION
**Pull request by StAlphonsos**
Many thanks to @avar for helping me with the git fu on IRC

### CODE REVIEW

**Comment by djcb** [comment]
Ah, great this got revived. There's a build-failure though, due to some missing `AM_PERL_MODULE`.

**Comment by StAlphonsos** [comment]
I'm sorry it took me so long to get back to this.  It appears that a
file got dropped from the commit: m4/perlmod.m4.  It looks like the
fact that m4/* appears in .gitignore screwed me a bit here and I
missed a file.  I've added it and pushed a second commit to my 639-redo
branch.  Sorry for the mess, is this okay?

I should also note that you need mup requires the Data::SExpression
CPAN module.  I don't know if you feel this should be noted somewhere
(README?).

**Comment by StAlphonsos** [comment]
ping?

**Comment by avar** [comment]
FWIW I intend to send some follow up fixes once this is merged. I think it
makes sense just to get it in first since it breaks no existing
functionality.

**Comment by StAlphonsos** [comment]
thanks a ton. just wanted to make sure i didn't somehow drop the ball again :-)

**Comment by avar** [comment]
@StAlphonsos I'm not the mu maintainer. I'm hoping he'll merge it, just giving him more incentive to do so.

**Comment by djcb** [comment]
Sorry for the delay -- traveling a bit. Anyway, very cool! Merging... Perhaps you can write a message to the mailing list with some details / examples?

**Pull request merged**
