### PR TITLE
Fedora spec

### PR DESCRIPTION
**Pull request by bojov**
This is an attempt to create a spec file for Fedora. It was tested almost a year over 4 releases. Packages can be found at [Fedora Copr](https://copr.fedorainfracloud.org/coprs/bojov/mu-fedora/).

### CODE REVIEW

**Comment by djcb** [comment]
Great, thanks. Can you squash it to  single commit?

**Comment by bojov** [comment]
Yes, it could be squashed to a single commit.

**Comment by djcb** [comment]
Thanks -- if you do that, I'll merge it.

**Comment by omajid** [comment]
Just as an FYI: this package was recently added to Fedora, under the name `maildir-utils`. The current Fedora spec file is here: https://src.fedoraproject.org/rpms/maildir-utils/blob/master/f/maildir-utils.spec

**Comment by djcb** [comment]
Oh, then it seems we shouldn't merge this... or?

**Comment by omajid** [comment]
IMHO, we shouldn't, for a couple of reasons:

- There's a spec file already in Fedora. This wont replace that unless @bojov works with the Fedora maintainers. If they work together, there's still nothing to be gained by putting a spec file here, I believe.
- If this spec file is meant as a guide for packagers for other distrbutions, we might as well just add a link and point it to Fedora's spec file 
- The package names are different because Fedora seems to have gone with Debian's `maildir-utlis` name
- The spec file is (thankfully!) actually mostly obvious and straightforward. It's not too difficult to create from scratch for someone familiar with spec files. (Compare this one to the rather more crazy spec files like [this one](https://src.fedoraproject.org/rpms/java-1.8.0-openjdk/blob/master/f/java-1.8.0-openjdk.spec)).
- There's a number of issues (not blockers, but they would need to be discussed and addressed in some way) in this spec file that would be flagged by Fedora folks during a review. Here's what I can spot quickly:
  - Inconsistency between spec file name (`mu.spec`) vs main package name (`mu-mail-search`)
  - The `Release` field is [very strage](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_simple_versioning).
  - The `Group` [tag is to be avoided](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_tags_and_sections)
  - The conflicts with `mu` ("A simple Python editor not only for micro:bit") is not ideal. Generally Fedora prefers to avoid conflicts if possible. 
  - `%Changelog` entries shouldn't contain macros like `%{gittime}`

**Comment by djcb** [comment]
Ok @omajid has some good comments, so I'll close this. Regardless, thanks for the effort, @bojov!

**Pull request closed without merging**
