### PR TITLE
Proposed action: show this thread only, meta-data in mu4e~headers-last-query

### PR DESCRIPTION
**Pull request by dkogan**
This is the pull request from the mailing list thread

https://groups.google.com/forum/#!topic/mu-discuss/IqowWeupeMk

### CODE REVIEW

**Comment by djcb** [comment]
Oh - thanks! But could you make a slightly less intrusive change, ie. just the action and the adding it in the header/view? The other changes are a (possible) next step, but may affect other people's setups, so let's wait with that.

**Comment by dkogan** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Oh - thanks! But could you make a slightly less intrusive change, ie.
> just the action and the adding it in the header/view? The other
> changes are a (possible) next step, but may affect other people's
> setups, so let's wait with that.

I'm not sure I follow. Are you suggesting that the action should just
search for the msgid, and leave it up to the user to enable
mu4e-headers-show-threads and mu4e-headers-include-related?

**Comment by djcb** [comment]
Yes; I suspect many users have include-related on by default already (and I'm going to make it the default behavior). show-threads is not strictly necessary (but also on by default).

**Comment by dkogan** [comment]
OK, how about the current tree then (just updated)? It only leaves the action, but at least turns on include-related and show-threads for that one search. This is simple, and will do the right thing the first time (and the first time only).

Oh, and making the query "previous_query AND msgid:xxx" has an issue: if include-related is on, then search results can contain messages that do not match the query, and a new query of ""previous_query AND msgid:xxx" would thus yield no results. The tree in this request still has the "previous_query AND msgid:xxx", but I think it should be changed back to "msgid:xxx"

**Comment by dkogan** [comment]
Hi again. Now that I've lived with this feature for a few days, I end up using it constantly, which is good. I'm also hitting the case very often where "previous_query AND msgid:xxx" yields no results. My workflow is to navigate to a particular folder (maildir: search) with include-related turned on, find an arbitrary message in a thread I'm interested in, and then invoke the new action in this patch. If I was lucky, the arbitrary message lives in the folder I searched for, and everything works. If I wasn't lucky, the message isn't there anymore, and I get no results. Let's go back to just "msgid:xxx".

**Comment by djcb** [comment]
The changes to mu4e-view / mu4e-headers gave a compilation error, because  the "(" and ")" were in the wrong places. I've fixed that, and also changed the query back to just msgid:xxx, and pushed it to master.

**Pull request closed without merging**
