### PR TITLE
[WIP] Start fixing cl-lib and lexical-binding issues

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
I started recently having weird errors about `incf`, after looking at the code, I see you are using both `cl` and `cl-lib` and `lexical-let` (part of `cl`) in some places and `lexical-binding` in other places.
I saw also an abusive usage of `add-to-list` (incompatible with lexical-binding in some places).
So I started a new branch to fix this, please have a look, it is not fully finished and tested, but I have no errors so far.
Thanks.

### CODE REVIEW

**Comment by djcb** [comment]
Overall, looks useful, thanks. What's the issue with the `add-to-list` vs `cl-pushnew`?
And since what emacs version are these new `cl-` functions available?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Overall, looks useful, thanks. What's the issue with the add-to-list
> vs cl-pushnew?

`add-to-list` is not working on lexical vars, generally it should not be
used in elisp programs, only in user configuration files.

I see in the places where I have replaced add-to-list by cl-pushnew you
was using the 'append argument of add-to-list which add the new element
at end of list instead of front, is it really important to do so?

> 
> And since what emacs version are these new cl- functions available?

The cl- functions I used here are not new, they exist since cl-lib have
been introduced, sure in emacs-24.1, maybe earlier don't remember.

Thanks.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
BTW we should add "-*- lexical-binding: t -*-" to all files for consistency, like this you don't have to think at lexical or dynamic when you write code.

**Comment by thierryvolpiatto** [comment]
Using now this branch since ten days without errors, do you want I rebase it to fix commit messages?

**Comment by djcb** [comment]
Oh, yes please. Then I can merge it. Thanks.

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Oh, yes please. Then I can merge it. Thanks.

I am now travelling, after mid september I will do it.

Thanks.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request closed without merging**
