### PR TITLE
Org mu4e compose stabilization

### PR DESCRIPTION
**Pull request by titaniumbones**
Hi Dirk-Jan,

Two small patches which I think fix some of the stability issuesi n org-mu4e-compose-org-mode.  With these patches, I can now add a hook to compose in html by default. I know this is not best practice, but I think there are many use cases for it, and while it would be better to fix org-mu4e-compose-org-mode entirely, this may help a fair number of people.

### CODE REVIEW

**Comment by stig** [comment]
Hi @titaniumbones, I manually applied https://github.com/djcb/mu/pull/952/commits/d60f58e8887ecec1d6692c846b69b80e91ec6a66 to my setup (I don't use any hooks, so didn't bother applying that changeset) but I don't think it has made a difference. I'm still seeing the "Message already sent, send again?" question. I selected no, and went to the header part and hit `C-c C-c` and it sent without errors.

**Comment by titaniumbones** [comment]
Maybe that change is irrelevant. I was thinking it might be.

However, I also rewrote John's htmlize-and-send function -- see my blog
here:

http://matt.hackinghistory.ca/2016/11/18/sending-html-mail-with-mu4e/

What are you using to send your mail? Can you try my code and see if it
helps?

**Comment by stig** [comment]
> What are you using to send your mail? Can you try my code and 
> see if it helps?

My current setup is here:
https://github.com/stig/dot-files/blob/master/emacs.d/Email.org

I don't tend to actually send HTML mail, I just like to edit it in 
org mode
(for footnotes etc). Because of that, moving to the header section 
and
pressing C-c C-c works fine for me. Actually sending from the body 
works fine
too, I just get that annoying warning.

As I don't want to send HTML emails automatically, I don't think 
your code is
exactly what I need.

**Comment by titaniumbones** [comment]
I think that you will need to make sure org-mu4e-org-compose-mode has been turned OFF before you send the message.  One option might be to rewrite the toggle function with an optional parameter that allows you to specify turning it off, and add that as a hook to the send function. Or something like that. Anyway, try turning the mode off manually before sending and see if it works?


Stig Brautaset writes:

>> What are you using to send your mail? Can you try my code and 
>> see if it helps?
>
> My current setup is here:
> https://github.com/stig/dot-files/blob/master/emacs.d/Email.org
>
> I don't tend to actually send HTML mail, I just like to edit it in 
> org mode
> (for footnotes etc). Because of that, moving to the header section 
> and
> pressing C-c C-c works fine for me. Actually sending from the body 
> works fine
> too, I just get that annoying warning.
>
> As I don't want to send HTML emails automatically, I don't think 
> your code is
> exactly what I need.


--

**Comment by averter** [comment]
For some reason I cannot get attachments right with this solution. Is there any particular trick to it? When I do `M-x mml-attach` I get the typical mu4e code
````
<#part type="image/jpeg" filename="~/example.jpeg" disposition=attachment>
<#/part>
````

**Comment by Chris00** [comment]
I think [OrgMsg](https://github.com/jeremy-compostella/org-msg) is a good alternative to compose HTML emails.  I supports attachments.

**Comment by djcb** [comment]
mu4e/org/compose has been deprecated for many years, closing this PR... perhaps OrgMsg can help?

**Comment by Chris00** [comment]
> perhaps OrgMsg can help?

Absolutely (one may even write maths and have images generated automatically).  Have not yet found the time to write something about it in the manual though.

**Comment by peterhoeg** [comment]
orgmsg is for writing in org and sending html. orgmsg also only kicks in when replying to an existing html mail (or when creating a new email).

My request was with regards to writing in org and sending either markdown or plain text (or html but orgmsg would handle that).

**Comment by Chris00** [comment]
> My request was with regards to writing in org and sending either markdown or plain text (or html but orgmsg would handle that).

Sending in plain text is no problem.  Just adapt the following to your liking:
```elisp
  (setq org-msg-default-alternatives '((new		. (text html))
				       (reply-to-html	. (text html))
				       (reply-to-text	. (text))))
```
Sending in `org` format is also possible.  It may be possible to register the [markdown exporter](https://www.orgmode.org/manual/Markdown-Export.html) in `org-msg-alternative-exporters`.

**Pull request closed without merging**
