### PR TITLE
Add new face for subject in mu4e-view

### PR DESCRIPTION
**Pull request by odi**
I would like to have a different face for the subject line in the mu4e-view.

This adds a new face for the subject in the mu4e-view. The default configuration inherits from mu4e-header-value-face, that means that there is no visual difference to the old configuration.

### CODE REVIEW

**Comment by davidcsterratt** [comment]
Thanks for the work, odi. This would be a feature I would like to see.

**Comment by Ambrevar** [comment]
Anything blocking a merge?

**Comment by antoine-levitt** [comment]
Can you explain the close? It looks like this is something quite a few people want, and I don't think it's implemented in master?

**Comment by djcb** [comment]
It's obsolete for the gnus-based view.

**Comment by antoine-levitt** [comment]
Is the old view going to be removed in future versions then? I like it better (and don't want to take the time to configure the gnus view to my liking)

**Comment by djcb** [comment]
Yes.

**Comment by antoine-levitt** [comment]
:(

**Comment by Chris00** [comment]
@antoine-levitt What don't you like in the Gnus based view?  It supports many messages that were improperly decoded by the old version.

**Comment by antoine-levitt** [comment]
Oh it's fine but I don't like the faces and it messes up with my hardwired patterns. More generally I feel like mu4e is breaking a lot of stuff and it's taking a lot of my energy to try to keep up - it's nice to see it move forward, but it does take time to adapt.

**Pull request closed without merging**
