### PR TITLE
Do not show trailing whitespace when viewing messages

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by djcb** [comment]
Hmm, isn't `show-trailing-whitespace` is `nil` by default?

**Comment by Chris00** [comment]
It is.  I saw that being done in Gnus — maybe an artifact of the past before the variable was buffer local?

**Comment by Chris00** [comment]
Specifically, you can [find it here](https://github.com/emacs-mirror/emacs/blob/master/lisp/gnus/gnus-art.el#L4521).  Maybe you would prefer it to be applied only when `mu4e-view-mode` derives from `special-mode` since it will be applied anyway in the other case?

**Comment by Chris00** [comment]
Now that `(setq show-trailing-whitespace nil)` is part of [`gnus-article-mode`](https://github.com/emacs-mirror/emacs/blob/master/lisp/gnus/gnus-art.el#L4451), it will eventually apply to mu4e.  Closing.

**Pull request closed without merging**
