### PR TITLE
Easy accounts with make-mu4e-context-account

### PR DESCRIPTION
**Pull request by Ambrevar**
Follow up on #1362 .

### CODE REVIEW

**Comment by djcb** [comment]
Nice work -- I'm ready to merge this, do you have any final changes?

**Comment by djcb** [comment]
(in particular, perhaps you could send a message to the mailing-list after the merge, so people will find out and you can take all credit :-) )

**Comment by Ambrevar** [comment]
Thanks!

No final change, but beware, this has only be tested in my simple use
case.  I suspect you'll have to update/fix some parts to accommodate
future user needs :)

**Comment by djcb** [comment]
Thanks -- I'll merge it, let's give it a test-run!

**Pull request merged**
