### PR TITLE
mu4e-actions: improve mbox handling for multiple marks

### PR DESCRIPTION
**Pull request by stsquad**
This contains 2 fixes. An update from the previous pull request #845 and a fix to drafting of messages which explains why some of my "related messages" started disappearing.

### CODE REVIEW

**Comment by stsquad** [comment]
I forgot to check outstanding pull requests, I note the references fix in in pull #871.

**Comment by djcb** [comment]
I took pull #871, can you update for the actions changes? Thank!

**Comment by stsquad** [comment]
@djcb : sure, done.

**Comment by djcb** [comment]
Thanks -- but can you give them a  bit more descriptive summary-line?

**Comment by stsquad** [comment]
I've updated with the commit message as there is no longer two fixes in this PR.

**Comment by djcb** [comment]
Merged -- thanks!

**Pull request merged**
