### PR TITLE
Adding support to query the headers of a message 

### PR DESCRIPTION
**Pull request by yellowmoneybank**
This pull-request adds support to search for headers in a message, specified
by its docid. This is necessary, if you want to add support for
protocols, that rely on adding header fields to mails (for example autocrypt).

The mu server is extended by the command "(header :docid <docid>
:header <header>)", and returns a message of the format "(:header
<header-fild> :docid <docid>  :value <header-field-value>)".

mu4e is extended by the function (defun mu4e~proc-header (docid
header) ...), which scans the message with the DOCID for a
HEADER-field.
The result of that function is delivered to the function registered as
"mu4e-search-header-field-func".

### CODE REVIEW

**Comment by djcb** [comment]
Hmm... appreciate the work, but not sure about this one. 

I'm not convinced `autocrypt` is worth supporting at this point. If `mutt` is the most prominent client supporting (with all due respect, I'm an old mutt user), it seems rather marginal -- not even `gnus` supports it. So the extra complexity seems unwanted.

Now, if we _do_ want to support it, it's probably better to add a few fields to the message sexp, using gmime's support. WDYT?

**Comment by phikal** [comment]
Actually, the most prominent client is Thunderbird. @yellowmoneybank and I have been working on a MUA-generic autocrypt implementation (the MELPA pull request is [here](https://github.com/melpa/melpa/pull/6767)), and while I managed to circumvent the need for this specific patch, I do feel that it would be more efficient than what [I came up with](https://git.sr.ht/~zge/autocrypt/tree/master/autocrypt.el#L502).

Furthermore, it's not just Autocrypt. There are certainly many more headers that add-ons could make use of if there were a sensible way to query them.

---

Also, GMIME has some difficulty implementing Autocrypt, since to my knowledge it isn't responsible for sending or has the ability to interject while composing messages? If this isn't given, it's rather difficult to add the `Autocrypt` header or the `Autocrypt-Gossip` attachment that is used for multiple recipients.

**Comment by djcb** [comment]
Ah, there's a 3rd-party extension for Thunderbird. Still I'd say it's rather marginal, but of course you have to start somewhere.

Anyway, I'm not in favor for querying of headers like this; the mu<->mu4e protocol is not designed for this, and it's not something I want to expose, either for autocrypt or other use-cases.

For the GMIME part, the idea would that in the sexps we send to mu4e when showing a full message, (mu-msg-sexp), we'd add the autocrypt header(s). I.e., you'd still get the same headers as in the 'query' case, but in a way that better fits mu4e.

**Comment by djcb** [comment]
Thanks for the effort, but this doesn't apply anymore, and anyway, I wasn't quite happy with the approach (as discussed above). So closing this...

**Pull request closed without merging**
