### PR TITLE
Travis: use recent autoconf 2.69 and recent autoconf-archive

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
P.S. Note that the `-bin` are [supposed to be deprecated](https://github.com/rejeep/evm#deprecation-warning).

**Comment by djcb** [comment]
Thanks!

**Comment by djcb** [comment]
BTW, Travis broke since mu now requires c++14...  @Chris00: do you know how to fix this?

**Comment by Chris00** [comment]
Does it help if you add the package that provides c++14 to `BUILD_PKGS` (in https://github.com/djcb/mu/blob/master/.travis.yml)?

**Pull request merged**
