### PR TITLE
Merged crypto-policy configuration into one variable

### PR DESCRIPTION
**Pull request by phikal**
The current cryptography policy is a bit confusing.  The existence of the two variables `mu4e-compose-crypto-reply-plain-policy` and `mu4e-compose-crypto-reply-encrypted-policy` at first glance implies that you can configure how to respond to encrypted and plain emails, but on closer inspection `mu4e-compose-crypto-reply-plain-policy` reveals itself to also be responsible for forwarding mails, creating new messages, etc.

This changeset suggests merging the two variables into one -- `mu4e-compose-crypto-policy` -- while at the same time expanding it's granularity. So instead of implementing `mu4e-compose-crypto-forward-plain-policy`, `mu4e-compose-crypto-new-policy`, etc. everything regarding encryption and signing is centrally controlled by a customizable set.

To avoid conflicts with older configurations, I have added a translation layer in `mu4e~compose-handler`, that adds the corresponding new symbols to the new policy variable, based on the old the values of the old variables. In case these weren't customized, both should be nil now, meaning that the append has no consing overhead (be it ever so minimal), as `mu4e-compose-crypto-reply-encrypted-policy` has been changed from `sign-and-encrypt` to nil. 

To preserve the current defaults, `mu4e-compose-crypto-policy` only contains the symbols that were implied by `mu4e-compose-crypto-reply-encrypted-policy`. It might be worth considering expanding the default configuration, but I didn't want to make that decision in this pull request.

### CODE REVIEW

**Comment by djcb** [comment]
At a glance, looks okay. But this will be something for post-1.4, as we are in deep-freeze mode.

**Comment by phikal** [comment]
No problem. Just out of curiosity, is there a planned release date?

**Comment by djcb** [comment]
Regarding the release: next few weeks, I think. There are still a few issues we're tracking.

**Comment by djcb** [comment]
Merged locally & pushed. Thanks!

**Pull request closed without merging**
