### PR TITLE
Fix empty 'To:' header on reply to icalendar invitation

### PR DESCRIPTION
**Pull request by mrvdb**
On reply to an ical invitation the To: header stayed empty, this fixes that.

The 'Reply-To' data is set if it is not there and if the emaill was different from the Organizer so
that the msg can be further treated by the draft construct functions.

This issue is briefly mentioned in issue #2305

### CODE REVIEW

**Comment by djcb** [comment]
@Chris00 ^^ does this look okay?

**Comment by mrvdb** [comment]
Just to make sure, is anything needed for this to get merged? Seemed like a fairly trivial change to me at the time. (I've been using it since then)

**Comment by djcb** [comment]
Looks fine to me, but I'm using icalendar. @Chris00: is there merge-ready?

**Comment by djcb** [comment]
No complaints from @Chris00, so merging this (well, cherry picked the change). Thank you!

**Pull request closed without merging**
