### PR TITLE
Make electric-quote-(local-)mode work when composing emails

### PR DESCRIPTION
**Pull request by Chris00**
electric-quote-(local-)mode used to have no effect because
`comment-use-syntax' was left to `undecided' so the electric mode was
not enabled for paragraphs.

Fixes https://github.com/djcb/mu/issues/997

### CODE REVIEW

**Comment by Chris00** [comment]
Since it is not possible to turn it off for certain portions of the text, I added a menu entry to toggle it—so one remembers how to do it when needed.

**Comment by djcb** [comment]
Thanks. Are you planning on updating this so headers / mml parts (and, i guess, code-blocks) are not affected by the electric-quote mode? Also note, electric-quote-mode only appeared with (iirc) emacs 25.1, so some fboundb check is needed.

**Comment by Chris00** [comment]
I do not think that it needs additional checks because `:enable (functionp 'electric-quote-local-mode)` will only enable it if `electric-quote-local-mode` is defined.  Or maybe you would like that the menu entry is not visible at all then `electric-quote-local-mode` is not defined?

**Comment by Chris00** [comment]
About headers, this is the same mode so I do not see how to turn electric quote selectively for them.

For mml parts, I am not sure what you want.  Since electric quote only changes quotes that one __types__, it will not affect mml parts.  May you be more precise?

**Comment by djcb** [comment]
Well, it's a corner-case, but I sometimes edit the mime-blobs (say for the mime type or the disposition), and wouldn't want to see fancy headers there. Same for the headers.

Now, the question is if that can be prevented... if `comment-start` would allow for a regexp, we could simply match the unwanted areas, and only enable it for paragraphs. But I see now that it's not easily possible; also the other items (strings and paragraps) are not easy to manipulate either  :-/ 

So, sadly not much we can do about that. I'll take your change then, if you add a comment for  the setting of `comment-use-syntax` (i.e, why are we setting it), and not show the menu item if emacs is too old.

**Comment by Chris00** [comment]
If I got you right, for mime-blobs, you should not have too much trouble as electric quote does not change the behavior of `"`.

I also opened a [bug against Emacs message mode](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25333).  Let's see if they think electric quote needs to be improved.  

I guess another way is to have several modes in the buffer and activate electric quote only for the mode active when typing text.

**Comment by djcb** [comment]
Ah, so, I meant that we can't really do anything more fancy than in your patch; anyway, I can merge it if you  can add a comment for the setting of `comment-use-syntax` (i.e, why are we setting it), and not show the menu item if emacs is too old. Thanks.

**Comment by Chris00** [comment]
Done.

**Comment by djcb** [comment]
Merged -- thanks!

**Pull request merged**
