### PR TITLE
Add support for displaying maildirs and their counts

### PR DESCRIPTION
**Pull request by seanfarley**
This code could be merged as-is but is mostly a request for comment on this functionality. In a nutshell, this upstreams the functionality of [mu4e-maildirs-extension](https://github.com/agpchil/mu4e-maildirs-extension) using the new query count feature. Displaying maildirs is disabled by default and controlled via `mu4e-main-show-maildirs`.

The last two commits that align both the bookmark and maildir counts is probably overkill but it does look nice.

Missing are documentation, updating the changelog, etc. but I can add those if this feature is deemed worthy to upstream :-)

### CODE REVIEW

**Comment by seanfarley** [comment]
Here are some screenshots to show what it all looks like:

Screen Shot 2020-02-24 at 2 49 35 PM

Screen Shot 2020-02-24 at 2 51 53 PM

**Comment by djcb** [comment]
Nice, I like it!

However, at least for now, I'd like to limit this to just the maildirs in `mu4e-maildir-shortcuts`.

(Note that I changed the format of those shortcuts to 
```
   (:maildir <maildir> :key <key>)
```
and optional `:hide` and `:hide-unread`. so very similar to `mu4e-bookmark` (the old format is still supported, you need the function `mu4e-maildir-shortcuts` which does the conversions from the old format; so I think we can handle those in the very same way. We can perhaps even turn them on by default (or only if there are not too many?)

Maybe after that we can add _all_ maildirs, but that may be quite a bit (e.g., I have 88 -- doesn't fit on the screen and I don't want to run 2 * 88 queries). So we'd need some filtering.

Other small thing: you need to quote the maildirs in the queries, like `(format "maildir:\"%s\"" maildir)` (still not perfect, but at least handles the not uncommon case of maildirs with spaces in them).

What do you think?

**Comment by seanfarley** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Nice, I like it!

Woohoo, thanks!

> However, at least for now, I'd like to limit this to just the maildirs in `mu4e-maildir-shortcuts`.
>
> (Note that I changed the format of those shortcuts to
> ```
>    (:maildir <maildir> :key <key>)
> ```
> and optional `:hide` and `:hide-unread`. so very similar to `mu4e-bookmark` (the old format is still supported, you need the function `mu4e-maildir-shortcuts` which does the conversions from the old format; so I think we can handle those in the very same way. We can perhaps even turn them on by default (or only if there are not too many?)

Aha! Yeah, that makes sense. I'll update the code to use those.

> Maybe after that we can add _all_ maildirs, but that may be quite a bit (e.g., I have 88 -- doesn't fit on the screen and I don't want to run 2 * 88 queries). So we'd need some filtering.

Oh, yeah, that's a good point. I'm always worried about making these
kind of changes since I think I have a fairly small mailbox and am
unaware of how other people use theirs and what kind of edge cases
exist.

I totally agree about limiting this to `mu4e-maildir-shortcuts` for now;
that will simplify the code a bit about missing keys.

Do you think we need a config variable for turning this off/on? Or will
checking `mu4e-maildir-shortcuts` for nil suffice?

> Other small thing: you need to quote the maildirs in the queries, like `(format "maildir:\"%s\"" maildir)` (still not perfect, but at least handles the not uncommon case of maildirs with spaces in them).

Ah, good catch, thanks!

> What do you think?

All those suggestions make sense for me! Once you let me know about
`mu4e-main-show-maildirs` needing to exist or not, I can also work on
some of the NEWS entries.

**Comment by seanfarley** [comment]
Sean Farley <sean@farley.io> writes:

> Dirk-Jan C. Binnema <notifications@github.com> writes:
>
>> Nice, I like it!
>
> Woohoo, thanks!
>
>> However, at least for now, I'd like to limit this to just the maildirs in `mu4e-maildir-shortcuts`.
>>
>> (Note that I changed the format of those shortcuts to
>> ```
>>    (:maildir <maildir> :key <key>)
>> ```
>> and optional `:hide` and `:hide-unread`. so very similar to `mu4e-bookmark` (the old format is still supported, you need the function `mu4e-maildir-shortcuts` which does the conversions from the old format; so I think we can handle those in the very same way. We can perhaps even turn them on by default (or only if there are not too many?)
>
> Aha! Yeah, that makes sense. I'll update the code to use those.
>
>> Maybe after that we can add _all_ maildirs, but that may be quite a bit (e.g., I have 88 -- doesn't fit on the screen and I don't want to run 2 * 88 queries). So we'd need some filtering.
>
> Oh, yeah, that's a good point. I'm always worried about making these
> kind of changes since I think I have a fairly small mailbox and am
> unaware of how other people use theirs and what kind of edge cases
> exist.
>
> I totally agree about limiting this to `mu4e-maildir-shortcuts` for now;
> that will simplify the code a bit about missing keys.
>
> Do you think we need a config variable for turning this off/on? Or will
> checking `mu4e-maildir-shortcuts` for nil suffice?
>
>> Other small thing: you need to quote the maildirs in the queries, like `(format "maildir:\"%s\"" maildir)` (still not perfect, but at least handles the not uncommon case of maildirs with spaces in them).
>
> Ah, good catch, thanks!
>
>> What do you think?
>
> All those suggestions make sense for me! Once you let me know about
> `mu4e-main-show-maildirs` needing to exist or not, I can also work on
> some of the NEWS entries.

Oh, one more question: what do you think about the logic to align both
the bookmarks unread count and the maildirs unread count? Keep it or is
it too much?

**Comment by djcb** [comment]
Oh, great!

As for a configuration variable...  good question. For now, I guess we can try without it, and let people turn of individual shortcuts with `:hide t` if they need to. If that turns out to be too annoying for too many people we can think of something.

Aligning the unread-count for bookmars and maildirs is a nice touch, yeah!

**Comment by seanfarley** [comment]
👍

**Comment by seanfarley** [comment]
Ok, I finally got around to updating this PR 😬 Hopefully, I addressed all the feedback!

There was one small design decision I made: in the main view there is now a "Maildirs" section below "Bookmarks" which will be empty if the user does not set any maildir shortcuts. I modeled this after the bookmarks logic and hope that it won't be a problem.

Sorry for the delay!

**Comment by djcb** [comment]
Great! I'll look at this post 1.4.x, hopefully soon.

**Comment by scturtle** [comment]
This does not work well with CJK maildir names.
There is encoding problem in `query` field of `mu4e~server-props`.
E.g. `(decode-coding-string (apply #'unibyte-string (string-to-list (plist-get q :query))) 'utf-8)` is need to make it a correct UTF-8 string.

**Comment by seanfarley** [comment]
Ah, thanks for the info!

**Comment by seanfarley** [comment]
Ah, this is also a problem in `bookmarks` too. Trying to fix now.

**Comment by seanfarley** [comment]
@djcb I put some fixes to the bookmarks section (an off-by-one error for the text property of mouse highlighting). Let me know if you want that in its own pull request separate from this one.

Also, @scturtle, I found it difficult to align the text of non-ASCII characters but that's due to my font. Here is a screenshot of my fix:

Screen Shot 2020-05-12 at 10 22 23 PM

**Comment by djcb** [comment]
I've merged this locally, with some tiny changes. Thanks for contributing!

**Pull request closed without merging**
