### PR TITLE
mu4e: add mu4e-update-timeout

### PR DESCRIPTION
**Pull request by j-hao**
I think this is useful if there was any issue and update process was stuck forever. I have personally encountered the same issue with isync and exchange 2016 just like https://sourceforge.net/p/isync/bugs/25/ and this allow me to workaround it.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Jun Hao <notifications@github.com> writes:

> I think this is useful if there was any issue and update process was
> stuck forever. I have personally encountered the same issue with isync
> and exchange 2016 just like https://sourceforge.net/p/isync/bugs/25/
> and this allow me to workaround it.

Perhaps it would be better to kill process instead of interrupt in
`mu4e-interrupt-update-mail` ?

Most of the time when hitting "S" interrupt-process is not enough to
stop the process.

Sometimes the update process is just very slow and not stuck forever, a
timeout would stop it instead of letting it finishing...

--
Thierry

**Comment by j-hao** [comment]
This PR is actually will kill process (if process is in running state) instead of interrupt it. So I think it matches your use case as well.

Also thanks for the info about `S` key. Don't know that :)

**Comment by thierryvolpiatto** [comment]
Jun Hao <notifications@github.com> writes:

> This PR is actually will kill process (if process is in running state)
> instead of interrupt it. So I think it matches your use case as well.

Yes, sending SIGKILL is better indeed, but using a timeout is not the
good approach IMO, it will stop the update on slow connections even when
no particular problem happens during this connection.

> Also thanks for the info about S key. Don't know that :)

Is using the "S" key with SIGKILL instead of SIGINT would fit your needs
?

I have a PR ready for this that allow configuring which signal to send
to update process to stop it among other things.

--
Thierry

**Comment by j-hao** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Jun Hao <notifications@github.com> writes:
>
>> This PR is actually will kill process (if process is in running state)
>> instead of interrupt it. So I think it matches your use case as well.
>
> Yes, sending SIGKILL is better indeed, but using a timeout is not the
> good approach IMO, it will stop the update on slow connections even when
> no particular problem happens during this connection.
>

I don't think we can tell is either a slow connection or an actual
issue. Any idea/suggestion?

>> Also thanks for the info about S key. Don't know that :)
>
> Is using the "S" key with SIGKILL instead of SIGINT would fit your needs
> ?
>
> I have a PR ready for this that allow configuring which signal to send
> to update process to stop it among other things.

Actually, "S" with SIGINT solves my issue and I just don't want to
manually run it every couple minutes. The connection appears to be
stuck forever. PS, by default, timeout won't run. I think these two
configuration doesn't conflict and can coexist.

-- 
Thanks - Jun

**Comment by thierryvolpiatto** [comment]
Jun Hao <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Jun Hao <notifications@github.com> writes:
>>
>>> This PR is actually will kill process (if process is in running state)
>>> instead of interrupt it. So I think it matches your use case as well.
>>
>> Yes, sending SIGKILL is better indeed, but using a timeout is not the
>> good approach IMO, it will stop the update on slow connections even when
>> no particular problem happens during this connection.
>>
>
> I don't think we can tell is either a slow connection or an actual
> issue. Any idea/suggestion?

Logging the process output (done in the ready PR I have here).
https://github.com/thierryvolpiatto/mu/tree/update_process

>>> Also thanks for the info about S key. Don't know that :)
>>
>> Is using the "S" key with SIGKILL instead of SIGINT would fit your needs
>> ?
>>
>> I have a PR ready for this that allow configuring which signal to send
>> to update process to stop it among other things.
>
> Actually, "S" with SIGINT solves my issue and I just don't want to
> manually run it every couple minutes. The connection appears to be
> stuck forever. PS, by default, timeout won't run. I think these two
> configuration doesn't conflict and can coexist.

Yes sure, I have no problems with the timeout, it will work fine for me
99% of the time even when enabled, just wanted to point out that a valid
connection but slow can be aborted for no reason by the timeout.

BTW note that you can use with-timeout to implement timeout here:

    (with-timeout (mu4e-update-timeout
                   (let ((status (process-status proc)))
                     (when (eq status 'run)
                       (kill-process proc))))
      [...])

Something like this.

-- 
Thierry

**Comment by djcb** [comment]
So, closing this. Thanks for the effort though!

**Pull request closed without merging**
