### PR TITLE
view-gnus: Add "Maildir" + fix decoding & highlighting issues

### PR DESCRIPTION
**Pull request by Chris00**
Fixes https://github.com/djcb/mu/issues/1269

### CODE REVIEW

**Comment by Chris00** [comment]
Some reordering of the decoding functions also fixes the highlighting of the headers — done by `gnus-article-prepare-display`.

**Comment by Chris00** [comment]
In the third commit, I removed
```
      (article-de-base64-unreadable)
      (article-de-quoted-unreadable)
```
because they cause problems with HTML messages — and B64 and quoted messages are decoded without those.

**Comment by djcb** [comment]
Would be good to separate the fixes from the new feature (and see the review comments).

I've found that it can be easy to fix some messages, yet breaking some others, so perhaps you can attach a (raw) message where this fixes things? Thnaks.

**Comment by Chris00** [comment]
Maildir feature: https://github.com/djcb/mu/pull/1303

**Comment by Chris00** [comment]
Fix header highlighting: https://github.com/djcb/mu/pull/1304

**Comment by Chris00** [comment]
> see the review comments

I do not see any.

**Pull request closed without merging**
