### PR TITLE
Spelling fixes and simplifying some code

### PR DESCRIPTION
**Pull request by sje30**

### CODE REVIEW

**Comment by sje30** [comment]
ignore this version.  have sent another version with further edits.

**Comment by sje30** [comment]
there should be two independent commits to the mu4e.texi 

1. some typos 
2. simplification of the gnus-dired section as most code has been folded into gnus-dired.el

**Comment by sje30** [comment]
https://github.com/djcb/mu/runs/2335441098 is failing on mac, but looks unrelated to the .texi edits.

**Comment by djcb** [comment]
Merged, thanks!

**Pull request merged**
