### PR TITLE
Quote Display Names which contain special characters

### PR DESCRIPTION
**Pull request by jaknel**
RFC 822 and RFC 5322 define characters which require an atom be quoted when included as a word in a mailbox.

### CODE REVIEW

**Comment by jaknel** [comment]
**Describe the bug**
An email address which ends up in the contact list database as `test@example.org <test@example.org>` needs to be quoted as `"test@example.org" <test@example.org>` when authoring an email in Mu4e

**To Reproduce**
```
From: test@example.org <test@example.org>
Date: 2023-06-03

Test
```
Index the above email using mu index on a Maildir. Then autocomplete the address while authoring an email in Mu4e.  If sent to an Office365 account the email will bounces as undeliverable (The date header above is included only to deal with variable `mu4e-compose-complete-only-after`)

**Environment**
Emacs and mu/mu4e all built from master on Ubuntu linux.

**Checklist**
- [ x] you are running either the latest 1.8.x/1.10.x release or `master` (otherwise, please upgrade).

**Comment by jaknel** [comment]
I believe this also resolves  #2466

**Comment by djcb** [comment]
Hmmm, the PR seems to do too much (and breaks the unit-tests); in practice, seems the RFCs are not followed and spaces, non-ascii UTF-8 are used without any problem. The Office365 may be a special case here; can't we fix that case by just adding '@' to the characters `needs_quoting` must test for?

**Comment by jaknel** [comment]
Patch 96e16034c70d549eac243b00579fe1e0ed1a22a5 added a check for ','  My first attempt added  '@' on top of that `if (c == ',' || c == '"' || c == '@')` and would resolve my specific issue. I'd agree the issue would be resolved with just that change.

This PR came from looking at the RFCs and trying to figure out what the Right Thing™ to do is.   I thought a more general fix could benefit others.  For example, an email with the mailbox: `first<last  <first.last@example.org>`  Mu will index the address, return the unquoted candidate to mu4e using auto complete, but then message-mode (gnus?) will complain `Email address first<last <first.last@example.org> looks invalid; send anyway? (y or n)` when sending the email.  However, if auto complete returned `"first<last"  <first.last@example.org>`  the email is sent without an issue.   

I've pushed a new commit which points to RFC5322 and that does not mark spaces, periods, or extended ascii as need quoting.  `make test` is also now successful.  But again, I would be ok with just '@' making it into the codebase.

**Comment by djcb** [comment]
This is the display-name, and gnus will still process it (e.g.,utf-8 encoding); so `display_name()` is not necessarily RFC-compliant. I've just pushed a change that adds the '@' , as suggested -- thanks!

(I'll think about those other cases)

**Comment by djcb** [comment]
No longer needed, so closing this; thanks!

**Pull request closed without merging**
