### PR TITLE
Guile 3.0 update, based on master.

### PR DESCRIPTION
**Pull request by dannyob**
This is the same set of patches as pull #1796 , except using master as the base. I just cherry-picked them, so you can accept either and then apply them to the other branch. Let me know if there was a smarter way to do this -- I'm eager to learn!

### CODE REVIEW

**Comment by djcb** [comment]
This looks useful, thanks! 

However guile is only as soft requirement, and this seems to make it a hard requirement.. i.e. from the CI:  
   https://github.com/djcb/mu/pull/1797/checks?check_run_id=1084030032

**Comment by dannyob** [comment]
Huh! I'll take a look at that!

**Comment by djcb** [comment]
Merged this locally, with a fix configure.ac. Thanks!

**Comment by dannyob** [comment]
Thank you!

**Pull request closed without merging**
